bind = "0.0.0.0:3000"
prefix = "paste"
max_ttl_secs = 86400
default_ttl_mins = 15
max_size = 8388608
max_pastes = 512
max_image_size = 20971520
lockdown = true
user = "user"
password = "pass"
secret = "change_me_secret"
session_ttl_secs = 28800
